spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT&useSSL=false
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: final-provider
  #rabbitMQ配置
  rabbitmq:
    host: 192.168.220.129
    port: 5672
    username: admin
    password: 1111
    virtual-host: /
server:
  port: 8091

mybatis:
  type-aliases-package: com.usian.pojo
